
baseurl = "/"
title = "Omar Trejo Navarro"

googleAnalytics = "UA-98004849-1"
languageCode = "en-us"
theme = "otrenav"

[params]

author = "Omar Trejo Navarro"
phrase = "The best ideas are common property."

description="""Hello! I'm a Data and Software Engineer who enjoys building
complex and valuable data platforms for organizations all over the world. My
background is in Machine Learning, Mathematics, and Economics, I was National
Data Science Champion for a contest organized by Mexico's Presidential Office in
2014, and I wrote [R Programming by
Example](http://links.omartrejo.com/r-programming-by-example). Let’s talk!"""

enableTwitterCard = true
twitterCardImage = ""
twitter = "otrenav"

enableRSS = true
enableToc = true

enableDisqus = true
disqusShortname = "otrenav"

postTags = false
enableSummary = true
showLatestPosts = false
useDescriptionReplaceSummary = false

# TODO: Test if this can be removed
enableGoogleAnalytics = true

customJS  = ["js/ensure-https.js", "js/contact-form.js"]
customCSS = ["css/contact-form.css"]

[social]

twitter-square = "http://links.otrenav.com/twitter/"
github-square = "http://links.otrenav.com/github/"
linkedin-square = "http://links.otrenav.com/linkedin/"
# youtube-square = "http://links.otrenav.com/youtube/"

[taxonomies]

tag = "tags"
