
baseurl = "/"
title = "Omar Trejo Navarro"

googleAnalytics = "UA-98004849-1"
languageCode = "en-us"
theme = "omartrejo"

[params]

author = "Omar Trejo Navarro"
phrase = "Data and Software Engineer"

description="""Hello! I'm a Data and Software Engineer who enjoys building
complex and valuable data platforms for organizations all over the world. My
background is in Machine Learning, Mathematics, and Economics. I was National
Data Science Champion for a contest organized by Mexico's Presidential Office
(2014), and I wrote [R Programming by
Example](http://links.omartrejo.com/r-programming-by-example) (2017). Let’s
talk!

<i>"There's nothing more powerful than an idea whose time has come."
<br>
—Víctor Hugo</i>
"""

enableTwitterCard = true
twitterCardImage = ""
twitter = "otrenav"

enableRSS = true
enableToc = true

enableDisqus = false
# disqusShortname = "otrenav"

postTags = false
enableSummary = true
showLatestPosts = false
enableGoogleAnalytics = true
useDescriptionReplaceSummary = false

customJS  = ["js/ensure-https.js", "js/contact-form.js"]
customCSS = ["css/contact-form.css"]

[social]

twitter = "http://links.omartrejo.com/twitter/"
gitlab = "http://links.omartrejo.com/gitlab/"
linkedin = "http://links.omartrejo.com/linkedin/"
youtube = "http://links.omartrejo.com/youtube/"

[socialpng]
keybase = "http://links.omartrejo.com/keybase/"

[taxonomies]

tag = "tags"
