
baseurl = "/"
title = "Omar Trejo Navarro"

googleAnalytics = "UA-98004849-1"
languageCode = "en-us"
theme = "omartrejo"

[params]

author = "Omar Trejo Navarro"
phrase = "Data and Software Engineer"

description="""Hello! I build data platforms and modern web applications with
Machine Learning components and open-source technologies around the Python,
JavaScript, and R ecosystems, and I help data-centric organizations, from all
over the world, get from idea to high-quality product very fast.

I've worked in a wide variety of projects, such as Machine Learning systems,
voice-enabled web applications, and blockchain products, among others, with
startups as well as Fortune 500 companies, and in in industries such as retail,
health, e-commerce, finance, security, and others.

My background is in Machine Learning, Mathematics, and Economics. I was National
Data Science Co-Champion for a contest organized by Mexico's Presidential Office
(2014), and I wrote [R Programming by
Example](http://links.omartrejo.com/r-programming-by-example) (2017).

Do you have an idea you want to bring to reality? Let’s talk!

<i>"There's nothing more powerful than an idea whose time has come."
<br>
—Víctor Hugo</i>
"""

enableTwitterCard = true
twitterCardImage = ""
twitter = "otrenav"

enableRSS = true
enableToc = true

enableDisqus = false
# disqusShortname = "otrenav"

postTags = false
enableSummary = true
showLatestPosts = false
enableGoogleAnalytics = true
useDescriptionReplaceSummary = false

customJS  = ["js/ensure-https.js", "js/contact-form.js"]
customCSS = ["css/contact-form.css"]

[social]

twitter = "http://links.omartrejo.com/twitter/"
gitlab = "http://links.omartrejo.com/gitlab/"
linkedin = "http://links.omartrejo.com/linkedin/"
# youtube = "http://links.omartrejo.com/youtube/"

[socialpng]

keybase = "http://links.omartrejo.com/keybase/"

[taxonomies]

tag = "tags"
