name = "OTRENAV"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = ["blog", "disqus", "rss", "syntax highlighting", "tags"]
features = ["blog", "disqus", "rss", "syntax highlighting", "tags"]
min_version = 0.20

[author]
name = "Omar Trejo"
homepage = "https://omartrejo.com"

[[original]]
name = "Cactus"
homepage = "https://themes.gohugo.io/cactus/"
repo = "https://github.com/digitalcraftsman/hugo-cactus-theme"
